---
title: "Analyse"
author: "JJayes"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r}
library(tidyverse)
theme_set(theme_light())
theme_update(
  # legend.position = "bottom",
  text = element_text(size = 14),
  legend.text = element_text(size = 14),
  plot.caption = element_text(size = 12)
)
library(sf)
```

```{r}
df <- read_rds(here::here("data", "roses-wolf", "data.rds"))
df_country <- read_rds(here::here("data", "roses-wolf", "data_country.rds"))
map_simple <- read_rds(here::here("data", "roses-wolf", "map_simple.rds"))
```

## Regional GDP

```{r}
library(gghighlight)

df %>% 
  filter(series == "Regional GDP (1990 $m)",
         country_current_borders == "Italy") %>% 
  ggplot(aes(year, value, colour = region)) +
  geom_point() +
  geom_line() +
  gghighlight(region %in% c("Calabria", "Lombardia")) +
  scale_y_continuous(labels = scales::dollar_format()) +
  scale_colour_brewer(palette = "Dark2") +
  labs(x = NULL,
       y = "Regional GDP (1990 $m)")
```

## Regional GDP per capita

```{r}
jpeg(here::here("figures", "regional_gdp_per_capita__line_1.jpeg"), width = 6, height = 4, units = "in", res = 1000)

df %>%
  filter(
    series %in% c("Population", "Regional GDP (1990 $m)"),
    country_current_borders == "Italy"
  ) %>%
  pivot_wider(names_from = series) %>%
  janitor::clean_names() %>%
  mutate(regional_gdp_per_capita = regional_gdp_1990_m / population * 1000000) %>%
  pivot_longer(c(regional_gdp_per_capita, population, regional_gdp_1990_m)) %>%
  filter(name == "regional_gdp_per_capita") %>%
  ggplot(aes(year, value, colour = region)) +
  geom_point() +
  geom_line() +
  gghighlight(region %in% c("Calabria", "Lombardia")) +
  scale_y_continuous(labels = scales::dollar_format()) +
  scale_colour_brewer(palette = "Dark2") +
  labs(
    x = NULL,
    y = "Regional GDP per capita (1990 $)"
  )

dev.off()
```


Map 
```{r}
df %>%
  filter(
    series %in% c("Population", "Regional GDP (1990 $m)"),
    country_current_borders == "Italy"
  ) %>%
  pivot_wider(names_from = series) %>%
  janitor::clean_names() %>%
  mutate(regional_gdp_per_capita = regional_gdp_1990_m / population * 1000000) %>%
  pivot_longer(c(regional_gdp_per_capita, population, regional_gdp_1990_m)) %>%
  filter(name == "regional_gdp_per_capita",
         year %in% c(1900, 1938, 1980, 2000)) %>% 
  inner_join(map_simple) %>% 
  ggplot(aes(geometry = geometry, fill = value)) +
  geom_sf() +
  facet_wrap(~ year) +
  theme_void() +
  scale_fill_gradient2(low = "blue", high = "red", midpoint = 30, labels = scales::percent_format(scale = 1)) +
  # scale_fill_continuous() +
  labs(fill = "Manufacturing employment")
```

## Sectoral Employment Shares

```{r}
jpeg(here::here("figures", "sectoral_employment_shares__stacked_area_1.jpeg"), width = 8, height = 6, units = "in", res = 1000)

df %>% 
  filter(series %in% c("Agric. share of employment",
                     "Industry share of employment",
                     "Services share of employment"),
         country_current_borders == "Italy") %>% 
  group_by(year, series) %>% 
  mutate(value = mean(value)) %>% 
  ungroup() %>% 
  distinct(series, year, value, .keep_all = T) %>% 
  mutate(region = "Italian Average") %>% 
  bind_rows(df %>% 
  filter(series %in% c("Agric. share of employment",
                     "Industry share of employment",
                     "Services share of employment"),
         region %in% c("Calabria", "Lombardia"))) %>% 
  ggplot(aes(year, value, fill = series)) +
  geom_area(position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_brewer(palette = "Spectral") +
  facet_wrap(~ region) +
  theme(legend.position = "bottom") +
  labs(x = NULL,
       y = "Sectoral share of employment",
       fill = NULL)

dev.off()
```


## Industry employment share

```{r}
jpeg(here::here("figures", "industry_employment_share__map.jpeg"), width = 8, height = 6, units = "in", res = 1000)


df %>%
  filter(
    series == "Industry share of employment",
    country_current_borders == "Italy",
    year %in% c(1900, 1938, 1980, 2015)
  ) %>%
  mutate(name = case_when(
    region == "Lombardia" ~ "Lombardia",
    region == "Calabria" ~ "Calabria",
    TRUE ~ ""
  )) %>%
  inner_join(map_simple) %>%
  ggplot(aes(geometry = geometry, fill = value)) +
  geom_sf() +
  geom_sf_text(aes(label = name)) +
  facet_wrap(~year) +
  theme(
    panel.grid = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "bottom"
  ) +
  guides(fill = guide_colorbar(barwidth = 15, barheight = .5, title.position = "top", title.hjust = .5)) +
  scale_fill_gradient2(low = "midnightblue", high = "red", mid = "pink", midpoint = 30, labels = scales::percent_format(scale = 1)) +
  labs(
    fill = "Share of employment in manufacturing",
    x = NULL,
    y = NULL
  )

dev.off()
```

## Agric shares

```{r}

jpeg(here::here("figures", "agric_employment_share__map_europe.jpeg"), width = 8, height = 6, units = "in", res = 1000)

df %>%
  filter(
    series == "Agric. share of employment",
    # country_current_borders == "Italy",
    year %in% c(1990, 2000, 2010, 2015)
  ) %>%
  mutate(name = case_when(
    # region == "Lombardia" ~ "Lombardia",
    region == "Calabria" ~ "Calabria",
    TRUE ~ ""
  )) %>%
  inner_join(map_simple) %>%
  ggplot(aes(geometry = geometry, fill = value)) +
  geom_sf() +
  geom_sf_text(aes(label = name), nudge_x = 7) +
  facet_wrap(~year) +
  theme(
    panel.grid = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "bottom"
  ) +
  guides(fill = guide_colorbar(barwidth = 15, barheight = .5, title.position = "top", title.hjust = .5)) +
  scale_fill_gradient2(low = "midnightblue", high = "red", mid = "pink", midpoint = 20, labels = scales::percent_format(scale = 1)) +
  labs(
    fill = "Share of employment in agriculture",
    x = NULL,
    y = NULL
  )

dev.off()
```


Population or population growth?

```{r}
jpeg(here::here("figures", "population_growth__line.jpeg"), width = 8, height = 6, units = "in", res = 1000)

df %>% 
  filter(country_current_borders == "Italy",
         series == "Population") %>%
  group_by(region) %>% 
  mutate(delta = (value - lag(value))/lag(value)) %>%
  ungroup() %>% 
  filter(year != 1900) %>% 
  ggplot(aes(year, delta, colour = region)) +
  geom_point() +
  geom_line()  +
  geom_hline(yintercept = 0, lty = 2) +
  gghighlight(region %in% c("Calabria", "Lombardia")) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_colour_brewer(palette = "Dark2") +
  labs(x = NULL,
       y = "Population growth rate")

dev.off()
```


```{r}
df %>% distinct(series)
```


```{r}


df_unemp <- read.csv(here::here("data", "italy-unemployment.csv")) %>% 
  as_tibble() %>% janitor::clean_names()

jpeg(here::here("figures", "unemployment_region__line.jpeg"), width = 8, height = 6, units = "in", res = 1000)

df_unemp %>% 
  ggplot(aes(time, value, colour = geo)) +
  geom_point() +
  geom_line()  +
  gghighlight(geo %in% c("Calabria", "Lombardia", "Italy")) +
  scale_y_continuous(labels = scales::percent_format(scale = 1, accuracy = 1)) +
  scale_x_continuous(labels = scales::number_format(scale = 1, accuracy = 1, big.mark = "")) +
  scale_colour_brewer(palette = "Dark2") +
  labs(x = NULL,
       y = "Unemployment rate")

dev.off()
```



```{r}
# install.packages("datapasta")
library(datapasta)

# datapasta::tribble_paste()
df_tourism <- tibble::tribble(
     ~V1,                            ~V2,          ~V3,
      1L,                       "Veneto", "69.229.094",
      2L, "Trentino-Alto Adige/Südtirol", "47.618.085",
      3L,                      "Tuscany", "41.152.681",
      4L,               "Emilia-Romagna", "40.647.799",
      5L,                     "Lombardy", "39.115.354",
      6L,                        "Lazio", "36.684.847",
      7L,                     "Campania", "21.689.412",
      8L,                       "Apulia", "15.197.186",
      9L,                      "Liguria", "15.183.243",
     10L,                       "Sicily", "15.135.259",
     11L,                     "Piedmont", "15.100.768",
     12L,                     "Sardinia", "14.940.111",
     13L,                       "Marche",  "9.656.538",
     14L,                     "Calabria",  "9.212.630",
     15L,        "Friuli-Venezia Giulia",  "9.022.550",
     16L,                      "Abruzzo",  "6.193.473",
     17L,                       "Umbria",  "6.081.647",
     18L,                 "Aosta Valley",  "3.606.308",
     19L,                   "Basilicata",  "2.603.624",
     20L,                       "Molise",    "482.051"
     ) %>% 
  rename(row = V1, region = V2, n_nights = V3) %>% 
  select(-row) %>% 
  mutate(n_nights = str_remove_all(n_nights, "\\."),
         n_nights = parse_number(n_nights))

jpeg(here::here("figures", "tourism__col.jpeg"), width = 8, height = 6, units = "in", res = 1000)

df_tourism %>% 
  mutate(region = fct_reorder(region, n_nights)) %>% 
  ggplot(aes(n_nights, region, fill = region)) +
  geom_col() +
  gghighlight(region == "Calabria") +
  theme(legend.position = "none") +
  scale_fill_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::number_format()) +
  labs(x = "Number of nights spent by tourists in 2018",
       y = NULL) 

dev.off()
```

